fix: pin `uv venv` to `inputs.python_version` to prevent venv recreation
* fixes
```
error: Failed to spawn: `basedpyright`
  Caused by: No such file or directory (os error 2)
```

Issue univention/dev/education/ucsschool-kelvin-rest-api#217